### ISSUE TITLE
Using GetAnime(MalId) on an entry with no RelatedAnime field returns a Json exception

### ISSUE THREAD

**Issue by siameseSerpent** [Ervie/jikan.net#1]
![jsonerror](https://user-images.githubusercontent.com/13861545/40027672-1a91f352-57a9-11e8-9d43-65bbdb7ba67b.PNG)

For reference, I am attempting to use GetAnime on the anime Key The Metal Idol
https://myanimelist.net/anime/1457/Key_the_Metal_Idol

Grabbing the basic info of the series directly from an AnimeSearchResult object works fine, but when I pull the MalID from the AnimeSearchResult object and then do GetAnime(MalId) in an attempt to get more detailed information, I receive this error.

**Comment by Ervie** [comment]
Nice catch, there was no unit test for this scenario. Thanks for providing reference.

Apparently the endpoint returns related anime as an empty array when there is none, but if there is at least one, they are packed into single object (which was currently handled). Same issue with GetManga() request.

Added a fix for that, it should be working in the new version.
