### ISSUE TITLE
getting manga's chapters and volumes names

### ISSUE THREAD

**Issue by baddotnet** [Ervie/jikan.net#10]
how can i obtain chapters names of a specific manga?
"GetMangaChapters" isn't there, while "GetAnimeEpisodes" exists

**Comment by Ervie** [comment]
Hello,

Jikan is unofficial API for MyAnimeList.net. Unfortunately, MAL does not offer chapter listing so it's not something we can parse/offer. In case of anime, there is a listing of episodes on most anime pages, like https://myanimelist.net/anime/1535/Death_Note/episode. Unless MyAnimeList add new feature with chapters/volumes listing on their page, getting chapter/volume titles from Jikan is not likely.

If this is key feature for you, I suggest you look into API for websites with this feature, like Kitsu.

**Comment by baddotnet** [comment]
i don't think kitsu provides that either. anyway its not a major thing, i'm pretty sure that i can do a workaround.
thank you for responding. 
keep up the good work
