### ISSUE TITLE
EpisodeVideo ImageURLs contain icon-banned-youtube.png

### ISSUE THREAD

**Issue by RexfelisLOC** [Ervie/jikan.net#13]
When getting the EpisodeVideo data for most shows I've tried (ie. Shingeki no Kyojin), all ImageURLs are "https://cdn.myanimelist.net/images/icon-banned-youtube.png".

**Comment by Ervie** [comment]
This is unfortunately expected result - this is current state for most videos on MAL. Check for example https://myanimelist.net/anime/16498/Shingeki_no_Kyojin/video - you can see that episodes videos are deprecated, while promotional videos are ok.

The best way would be ask MAL to fix data on their side.

**Comment by Ervie** [comment]
Not related to wrapper or Jikan implementation.

**Comment by RexfelisLOC** [comment]
I got really busy with a project and could not respond.  I'm just referencing the ImageUrls, not the videos themselves.  With the link you provided, you can see the images are still there.

**Comment by RexfelisLOC** [comment]
Take a look at this:

[https://ibb.co/gZGsCQs](url)

**Comment by Ervie** [comment]
I still get same image you posted on the opening post. Checking https://api.jikan.moe/v3/anime/16498/videos (which is API endpoint in this case) yields the same result. I think this is related to the country in which server with Jikan rest instance is hosted in - Crunchyroll might have regional blockade on it. I would suggest to host own instance of jikan-rest in country without blockade (USA would be best shot). Please refer to https://github.com/jikan-me/jikan for more help.

**Comment by RexfelisLOC** [comment]
Thanks, I'll give that a shot.
