### ISSUE TITLE
AnimeSearchConfig excluded genres don't behave as expected

### ISSUE THREAD

**Issue by JaoHundred** [Ervie/jikan.net#17]
Hi Ervie, I was trying to implement AnimeSearchConfig filters and noticed the end point of excluded genres is not behaving as expected. I've Tried to fill 5 genres for exclusion(and marked the boolean property "GenreIncluded" as false), the returning collection was empty. I've checked as well MAL website, there it works removing the searched animes which has any genres specified for exclusion.

Steps to reproduce:

Expected:
- create a AnimeSearchConfig object with sort by score and descending
- fill genres with "hentai", "yaoi", "yuri", "ecchi", "harem"
- set the GenreIncluded property as false
- collection return without animes of the specified genres

Actual behavior:
- create a AnimeSearchConfig object with sort by score and descending
- fill genres with "hentai", "yaoi", "yuri", "ecchi", "harem"
- set the GenreIncluded property as false
- collection return empty

**Comment by Ervie** [comment]
Thanks for the ticket - at first it looks like the condition for genre inclusion/exclusion at fault. I reproduced your scenario with both library and on MyAnimeList and search results are empty if select "Include" on MAL but the other way around when selected "Exclude".

I will confirm this is wrapper issue and if possible release version 1.4.2 with applied fix.

**Comment by Ervie** [comment]
Version 1.4.2 with fix was pushed and should be visible shortly.

**Comment by JaoHundred** [comment]
Thank you!
