### ISSUE TITLE
Endpoint for News

### ISSUE THREAD

**Issue by JaoHundred** [Ervie/jikan.net#18]
Hi Ervie, I noticed there's no news endpoint at "https://myanimelist.net/news", only news for specific animes is currently covered at "https://myanimelist.net/anime/{id}/news)". Will this be covered in the future?

**Comment by Ervie** [comment]
Not at this moment - current Jikan REST API does not have an endpoint for news (other the afromentioned endpoint for specific anime and manga). Guys are working extensively at v4 alpha at this moment and I don't think want to add this endpoint at this point for v3 API.
Answering your question: yes, it will be covered, but likely when v4 is released (and wrapper is updated to work with it). But I do not have an answer when it will be ready. Roughly September?

**Comment by JaoHundred** [comment]
I see, thank you for your answer. I will keep an eye at the Jikan Discord for further future information.

**Comment by Ervie** [comment]
Closing for now, might be a goal when API v4 is ready.
