### ISSUE TITLE
Can I use this library to add elements to the logged user watch (or read) list and set the last watched (or read) episode (or chapter) ???

### ISSUE THREAD

**Issue by beppe9000** [Ervie/jikan.net#2]

**Comment by Ervie** [comment]
Hi,

Unfortunately not, as Jikan API was created to supplement official MAL API provided by MyAnimeList, which is limited mainly to adding/editing/removing entries on users' lists. Main difference between Jikan and official API is, that you don't have to provide credentials to make requests on Jikan API. I suggest you to integrate official MAL for these functionalities at this moment. Endpoint for this API is at: http://myanimelist.net/api/ There should be a documentation for this API on MAL, and I guess you can easily find .NET wrappers.

Creator of the API mentioned that he will probably at some point wrap existing endpoints to MAL API in Jikan, so  you won't have to use separate two APIs.

Jikan.net should also be updated in near future for loading data about users (profile, friends, history, manga/anime list), as soon as I find a bit of free time to extend the library.

**Comment by beppe9000** [comment]
I guess I will have to wait at least until they revive the official API...

![image](https://user-images.githubusercontent.com/6625123/47362299-66beef00-d6d4-11e8-9c9d-b8fc248afbb4.png)
