### ISSUE TITLE
Anime Character About is empty

### ISSUE THREAD

**Issue by JaoHundred** [Ervie/jikan.net#21]
Hi Ervie, after update 1.5.0 the property About from Character is empty.

Steps to reproduce:

Use GetCharacter(CharacterMALid) on Jikan version 1.4.2 to get any character which has a description (About property)

 **Expected behavior:** character which has description on MAL will have text on About property
 **Actual behavior:** text exist inside About property

Use GetCharacter(CharacterMALid) on Jikan version 1.5.0 to get any character which has a description (About property)

 **Expected behavior:** character which has description on MAL will have text on About property
 **Actual behavior:** About property is empty

**Comment by Ervie** [comment]
Hi, thank you for reporting this issue. After quick check, I confirmed that it's the bug in the newer version (System.Text.Json is less forgiving when it comes to parsing).

I will fix that and release version 1.5.1.

**Comment by Ervie** [comment]
New version is available, please update references in your project.

Again, thanks for notice.

**Comment by JaoHundred** [comment]
Thank you.
