### ISSUE TITLE
Ratelimiting support

### ISSUE THREAD

**Issue by kotx** [Ervie/jikan.net#22]
It would be appreciated to have an interval between requests as a optional parameter. It would be good to support custom ratelimits for self-hosted APIs as well. 
As of now the ratelimits for the main instance jikan.moe are:
> Daily Limit: Unlimited
30 requests / minute
2 requests / second

Bulk requests must be 1 request / 4 seconds.

**Comment by Ervie** [comment]
Not a bad idea, I will give it a thought and check if it's worth it when I have a little more free time. I'll keep it issue open for now.

**Comment by vynxcc** [comment]
@Ervie i would also love to have this

**Comment by Ervie** [comment]
This was added as a part of 2.6.0 thanks to @aetherstrata 
Will add a page on wiki about this later
