### ISSUE TITLE
[Proposal] Add new constructor to Jikan class

### ISSUE THREAD

**Issue by N0D4N** [Ervie/jikan.net#23]
Add new constructor to `Jikan` class which accepts custom, user-provided `HttpClient`.

#### Reasoning
With this feature user will be able to provide custom `HttpClient` with preconfigured [HttpMessageHandler](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpmessagehandler?view=net-5.0), make `HttpClient` resilient with [Polly](https://github.com/App-vNext/Polly) for example etc.

Currently it is possible to achieve the same thing via reflection or with implementing `IJikan` interface and making such constructor, however both ways are looking tricky  to me.

#### Proposed API
```cs
/// <summary>
/// Constructor.
/// </summary>
/// <param name="httpClient">Http client to call REST request and receive REST response</param>
/// <param name="suppressException">Should exception be thrown in case of failed request. If true, failed request return null.</param>
public Jikan(HttpClient httpClient, bool suppressException = false)
{
_suppressException = suppressException;
_httpClient = httpClient
}
```
Optionally check `httpClient` instance for being null.

I can make a PR for this.

**Comment by Ervie** [comment]
Sounds reasonable, I'll add it. One disadvantage of that would be that user has to take care to prepare endpoint for HttpClient themselves - I think it should be documented.

Also when Jikan v4 will hit, next version will be probably tagged as 2.0 and have constructor reworked to avoid creating infinite combinations - probably one parameterless and second with object (maybe named `JikanOptions` or something similar).

**Comment by Ervie** [comment]
Done, version 1.5.3 should be visible shortly.
