### ISSUE TITLE
[Proposal] Make argument check on enums to make sure they are valid before making HTTP request

### ISSUE THREAD

**Issue by N0D4N** [Ervie/jikan.net#28]
## Reasoning
Currently jikan.net doesn't make any checks on any enums passed as parameters to methods of `Jikan` class, so its possible to pass int casted to enum to method which will result in making HTTP request and failing on parsing response from Jikan server.  

## Proposal
Add method `IsValidEnum` or `IsDefinedEnum` to `Guard` class which will check if passed parameter is defined enum. Add checks for validity of enums passed in methods.

## Drawbacks
Execution time of method with added checks will increase, and i'm not sure if its worth it for safechecking for such edge cases.

### Note
I can make PR for this.

**Comment by Ervie** [comment]
There's always someone who will think of a scenario you won't :) 

I agree that adding such validation method is a good idea, even if it's statistically much less probable than passing wrong string or int value. You can either make a PR for that (and I will review and merge, then release a new version alongside another fix you have made for `SearchManga` method) or you can a wait a bit and I'll do it myself (most likely in 2 weeks, being quite busy for now).

As for execution time, it will be a miniscule - likely 1-5 added miliseconds, when fetching http response from Jikan is 150-200 ms for cached values, around 700-1200 ms for non-cached. IMO it's worth it.

**Comment by N0D4N** [comment]
I'll make a PR

**Comment by Ervie** [comment]
Both changes were included in nuget 1.5.6, which should be visible shortly.

**Comment by N0D4N** [comment]
Nice, thanks!
