### ISSUE TITLE
version 1.6.0 change notes?

### ISSUE THREAD

**Issue by JaoHundred** [Ervie/jikan.net#31]
Hi Ervie, is there any place I can see the change notes for version 1.6.0?

**Comment by Ervie** [comment]
Duh, seems like forgetful me did not push changes to the repository. I've just pushed them now.
For more information about genre enumeration, see here: https://jikan.docs.apiary.io/#reference/0/search
I'll update the wiki later

**Comment by JaoHundred** [comment]
Everyone has forgetful moments, thanks again Ervie.
