### ISSUE TITLE
GetPerson request failed

### ISSUE THREAD

**Issue by Arzack010** [Ervie/jikan.net#33]
I think its because myanimelist.net change person to people in url
https://myanimelist.net/person/{id} return an error
the correct url that return a data is:
https://myanimelist.net/people/{id}

**Comment by Ervie** [comment]
Hi, if that was a case, the issue would be related to main [Jikan Api](https://github.com/jikan-me/jikan).

However, I tested few calls from library and they were successful. Can you post an example of the person id that failed for you? From top of my head, there's a list for possible causes:
- There's no person under this id (it happens sometimes on MAL)
- You are being rate limited and need to lessen amount of calls (see [documentation of the API](https://jikan.docs.apiary.io/#:~:text=the%20Wrapper%20List-,Rate%20Limiting,-Daily%20Limit%3A%20Unlimited))
- Internal MAL issues, e. g. site is down

But would be best to work on example. I also suggest to check the exception message and code in thrown exception.

**Comment by Arzack010** [comment]
I try with the same example from the wiki
![example](https://user-images.githubusercontent.com/85657671/147536144-df1488ec-0dbe-4634-89b7-b768eeff319e.jpg)

according of the wiki the method GetPerson parses item data by ID from https://myanimelist.net/person/{id} 
but if you go to [https://myanimelist.net/person/1870](url) you get a "404 Not Found"

**Comment by Ervie** [comment]
It's working for some ids (lik 1 or 7), but failing for few different. I created a an issue on official API repo, we'll see how they respond. If it's fixed on API side, then this wrapper should work automatically.

**Comment by Ervie** [comment]
He already fixed that. You can check it on your side.

**Comment by Arzack010** [comment]
Thanks, it works
