### ISSUE TITLE
Injectable HttpClient for the HttpClientFactory pattern

### ISSUE THREAD

**Issue by kuru-rin** [Ervie/jikan.net#37]
It is currently not possible to inject my own `HttpClient` using IoC. 

Also then instead of the `Endpoint` property in the client config, using the HttpClientFactory pattern one could do this as well:
```cs
services.AddHttpClient<IJikan, Jikan>(client => {
  client.Timeout = TimeSpan.FromSeconds(10);
  client.BaseAddress = new Uri(/* your endpoint */)
});
```

See this page for even more benefits: https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests

**Comment by Ervie** [comment]
I'll have a look at this and https://github.com/Ervie/jikan.net/issues/36 in the following days, when I find some free time.

**Comment by Ervie** [comment]
I pushed version 2.2.0, that allows injecting own HttpClient and use it with DI.
I'll keep `Endpoint` in the configuration until version 2.3.0 - it will be just marked as obsolete.

**Comment by kuru-rin** [comment]
Very nice. Thanks for your efforts!
