### ISSUE TITLE
Interface for Anime item and Manga item

### ISSUE THREAD

**Issue by flashkid10** [Ervie/jikan.net#4]
Is there a way to for you to add an Interface for the Anime item and Manga item so I can treat them as the same item to help with accessing internal propertys.

So instead of doing something like this;
`public long ID { get { if (AnimeItem!= null) return AnimeItem.MalId; else return MangaItem.MalId; } }`

I can reference the ID though a interface (or a series of interfaces) , like this
```
public interface MalItemInteracter
    {
        long MalId { get; }
        string Title { get; }
        string Studios { get; }
        string Type { get; }
        string Author { get; }
        string Genres { get; }
        float? Score { get; }
    }

MalItemInteracter MII = (AnimeItem or MangaItem) as MalItemInteracter();
public long ID { get { MalItemInteracter.MalId; } }
```

**Comment by Ervie** [comment]
Hi,

In new version (1.2) both Manga and Anime (and few other classes) share `IMalEntity` interface which allow you to reference to items by `MalId`. Documentation should be updated in the near future.
