### ISSUE TITLE
the current way to use titles is marked as deprecated

### ISSUE THREAD

**Issue by Fribb** [Ervie/jikan.net#40]
With the current APIv4 you have the JSON elements for the titles separately available.

* title
* title_english
* title_japanese
* title_synonyms

Those are marked as Deprecated according to the documentation [here](https://docs.api.jikan.moe/#tag/anime/operation/getAnimeById) 

The new way combines all of the titles under a single element `titles`, example:

```
"titles": [
      {
        "type": "Default",
        "title": "One Piece"
      },
      {
        "type": "Synonym",
        "title": "OP"
      },
      {
        "type": "Japanese",
        "title": "ONE PIECE"
      },
      {
        "type": "English",
        "title": "One Piece"
      }
    ],
```

**Comment by Ervie** [comment]
That's true. I've started implementing the change (there's more of them), but I'm leaving for vacation tomorrow. When I'll be back, I'm going to do rest of them, including this one.

**Comment by Ervie** [comment]
Titles property for Manga and Anime were just added in version 2.3.0 (should be available today). The old properties has been marked as obsolete and removed in version 2.4.0 (whenever it will be released).
