### ISSUE TITLE
Retrieving next page from GetUpcomingSeasonAsync

### ISSUE THREAD

**Issue by DeamonKira** [Ervie/jikan.net#41]
Is there any way to retrieve next page from `GetUpcomingSeasonAsync` method? Now it returns 25 records from first page with pagination data but with no option to set the number of page or am I missing something? Thank you

**Comment by Ervie** [comment]
Looks like there's missing parameter passing. I'll try to look at it at the weekend.

**Comment by Ervie** [comment]
A version of that method was just added in version 2.3.0 (should be available today).
