### ISSUE TITLE
GetSeasonAsync doesn't have page param

### ISSUE THREAD

**Issue by JaoHundred** [Ervie/jikan.net#43]
I noticed the `GetSeasonAsync` method doesn't have overload with `page` param, in Jikan rest api it has a query param to `page`.

**Comment by Ervie** [comment]
Thanks, will check tomorrow

**Comment by Ervie** [comment]
Added method with paging in version 2.4.1.

**Comment by JaoHundred** [comment]
Just checked, now I can pass pages. I saw some weird thing where the consecutive pages get Anime dupes, checked the jikan API and tried to reproduce this, the consecutive pages returned as expected(no anime dupes). Should I open a new issue for this?

**Comment by Ervie** [comment]
Hmm, weird. Can you try to reproduce it? I wrote a short code snippet to test that:
![image](https://user-images.githubusercontent.com/7793434/201997051-01e586da-cc75-43c5-9da6-ec4d594540f1.png)

The results are different, with no dupes:
![image](https://user-images.githubusercontent.com/7793434/201997183-0503f0fb-aa7c-4854-8253-1d42e28eceff.png)

They are equivalents of `https://api.jikan.moe/v4/seasons/2020/summer` and `https://api.jikan.moe/v4/seasons/2020/summer?page=2` respectively

**Comment by JaoHundred** [comment]
Sure, I will take a look at this.

**Comment by JaoHundred** [comment]
I feel dumb now, the error was on my end, I was calling twice the first response to fetch the data, sorry for wasting your time with this silliness and thanks for the support.

**Comment by Ervie** [comment]
No worries, happens to everyone. Just a part of programmer's life :)
