### ISSUE TITLE
GetSeason needs params - current season?

### ISSUE THREAD

**Issue by andzejsp** [Ervie/jikan.net#44]
My app broke cuz someone decided to move the API version up.. how do i get current season? it sued to be just GetSeason, your documentation shows that it still works but in 2.4.0 it does not accept it without params

**Comment by Ervie** [comment]
I see that the method is missing. I'll check it tomorrow

**Comment by Ervie** [comment]
Added method GetCurrentSeasonAsync in version 2.4.1. That should cover your scenario. You can optionally pass page to get next batch of data.
