### ISSUE TITLE
JikanApiError is not being deserialized correctly

### ISSUE THREAD

**Issue by kuru-rin** [Ervie/jikan.net#45]
It looks like the `JikanApiError` model does not get its properties filled.
Most likely due to the properties being `private set`?

**Comment by Ervie** [comment]
You're right

**Comment by Ervie** [comment]
Tested it, fixed and pushed version 2.4.2 - should be available now.

**Comment by kuru-rin** [comment]
I can confirm. Thanks for the quick fix!
