### ISSUE TITLE
 Jikan API v3.2 Update

### ISSUE THREAD

**Issue by irfan-dahir** [Ervie/jikan.net#5]
Hi, I just released Jikan v3.2. It has some new additions and changes, thought I'd let wrapper devs know directly.

## New Features
- Anime/Manga Reviews, Recommendations, User Updates
- Club Information, Members
- Season Later

### Reviews
**Anime**
```
GET /v3/anime/{id}/reviews/{page}
```
**Manga**
```
GET /v3/anime/{id}/reviews/{page}
```

**Remarks:** Only 20 items are shown per page for reviews

### Recommendations
**Anime**
```
GET /v3/anime/{id}/recommendations
```
**Manga**
```
GET /v3/anime/{id}/recommendations
```

### User Updates
**Anime**
```
GET /v3/anime/{id}/userupdates/{page}
```
**Manga**
```
GET /v3/anime/{id}/userupdates/{page}
```

### Season Later
```
GET /v3/season/later
```

### Club Information
```
GET /v3/club/{id}
```

### Club Members
```
GET /v3/club/{id}/members
```

## Changes
- All data from user related endpoints /v3/user/* are now cached for 5 minutes only
- (Anime/Manga) Bug fixed for related property. It's an object but returns an array when it was empty. This is fixed now.
- Error messages are now different and readable.

**Documentation:** https://jikan.docs.apiary.io

**Comment by Ervie** [comment]
All new endpoints and changes covered.
