### ISSUE TITLE
OS

### ISSUE THREAD

**Issue by hi5kba** [Ervie/jikan.net#9]
Is this windows 10 package Manager?
Or do i need to install a piece if software first. E.G Node.js?

**Comment by Ervie** [comment]
Hello,

The afromentioned Package Manager is Nuget Package Manager- Visual Studio IDE tool for downloading, installing, upgrading, configuring, and removing packages from a Visual Studio Project. It is bundled by default in newer versions of Visual Studio and is accessible from VS itself. Visual Studio IDE is a software for Windows system (there is a version fo Macs which should work too, but I did not try that).

An alternative is .Net CLI - command line interface for .Net Core (cross-platform implementation, working on Linux, MacOs and Windows alike). It requires installed .Net Core SDK and works similar to other console tools like Node's npm or PHP's Composer/Packagist.
